spring:
  application:
    name: "jpashop"
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/db/bookstore
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        # 위에 얘는 system out 으로 출력
        format_sql: true

logging.level:
    org.hibernate.SQL: debug
    # 얘는 log 로 출력 그래서 이걸 사용하는 걸 권장함
    org.hibernate.orm.jdbc.bind: trace