spring:
  application:
    name: "store"
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/db/bookstore
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create


